modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL = "https://github.com/JevenDev/Gracebound/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# Gracebound uses a runtime hello handshake for enhanced mode, so clients can safely connect to servers without Gracebound.
displayTest="IGNORE_SERVER_VERSION"
logoFile="logo.png"
authors="jvn"
displayURL="https://modrinth.com/mod/gracebound/"
description='''
May grace guide your way.
'''

#[[mixins]]
#config="gracebound.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="xaerominimap"
type="optional"
versionRange="[1.21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="xaeroworldmap"
type="optional"
versionRange="[1.21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="antique_atlas"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
